version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: tms_postgres
    environment:
      POSTGRES_DB: translationengine
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    image: tms_app:latest
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: translationengine
      DB_USERNAME: postgres
      DB_PASSWORD: secret
    restart: on-failure

volumes:
  postgres_data:
